name: Deploy PRD
on:
  push: 
    tags:  
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  IMAGE: r4deu51/chat-realtime-anonymous
  TAG: ${{ github.ref_name }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Config QEMU
        uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: linux/amd64

      - name: Config Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
        with:
          platforms: linux/amd64

      - name: Login in Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish Image to Docker
        run: make deploy IMAGE=${{ env.IMAGE }} TAG=${{ env.TAG }}

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout code 
        uses: actions/checkout@main

      - name: Deploy Image
        uses: ramonpaolo/action-zenifra@main
        with:
          PROJECT_ID: ${{ secrets.ZENIFRA_PROJECT_ID_PRD }}
          API_KEY: ${{ secrets.ZENIFRA_API_KEY_PRD }}
          IMAGE: "${{ env.IMAGE }}:${{ env.TAG }}"

